package com.fastjrun.demo.entity;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.loginName
     *
     * @mbg.generated
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.loginPwd
     *
     * @mbg.generated
     */
    private String loginpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mobileNo
     *
     * @mbg.generated
     */
    private String mobileno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.nickName
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbg.generated
     */
    private Short sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.lastModifyTime
     *
     * @mbg.generated
     */
    private Date lastmodifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.lastLoginTime
     *
     * @mbg.generated
     */
    private String lastlogintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.loginErrCount
     *
     * @mbg.generated
     */
    private Short loginerrcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.lastRecordLoginErrTime
     *
     * @mbg.generated
     */
    private String lastrecordloginerrtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.loginName
     *
     * @return the value of t_user.loginName
     *
     * @mbg.generated
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.loginName
     *
     * @param loginname the value for t_user.loginName
     *
     * @mbg.generated
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname == null ? null : loginname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.loginPwd
     *
     * @return the value of t_user.loginPwd
     *
     * @mbg.generated
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.loginPwd
     *
     * @param loginpwd the value for t_user.loginPwd
     *
     * @mbg.generated
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd == null ? null : loginpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.mobileNo
     *
     * @return the value of t_user.mobileNo
     *
     * @mbg.generated
     */
    public String getMobileno() {
        return mobileno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.mobileNo
     *
     * @param mobileno the value for t_user.mobileNo
     *
     * @mbg.generated
     */
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno == null ? null : mobileno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nickName
     *
     * @return the value of t_user.nickName
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nickName
     *
     * @param nickname the value for t_user.nickName
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sex
     *
     * @return the value of t_user.sex
     *
     * @mbg.generated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sex
     *
     * @param sex the value for t_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.createTime
     *
     * @return the value of t_user.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.createTime
     *
     * @param createtime the value for t_user.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.lastModifyTime
     *
     * @return the value of t_user.lastModifyTime
     *
     * @mbg.generated
     */
    public Date getLastmodifytime() {
        return lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.lastModifyTime
     *
     * @param lastmodifytime the value for t_user.lastModifyTime
     *
     * @mbg.generated
     */
    public void setLastmodifytime(Date lastmodifytime) {
        this.lastmodifytime = lastmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.lastLoginTime
     *
     * @return the value of t_user.lastLoginTime
     *
     * @mbg.generated
     */
    public String getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.lastLoginTime
     *
     * @param lastlogintime the value for t_user.lastLoginTime
     *
     * @mbg.generated
     */
    public void setLastlogintime(String lastlogintime) {
        this.lastlogintime = lastlogintime == null ? null : lastlogintime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.loginErrCount
     *
     * @return the value of t_user.loginErrCount
     *
     * @mbg.generated
     */
    public Short getLoginerrcount() {
        return loginerrcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.loginErrCount
     *
     * @param loginerrcount the value for t_user.loginErrCount
     *
     * @mbg.generated
     */
    public void setLoginerrcount(Short loginerrcount) {
        this.loginerrcount = loginerrcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.lastRecordLoginErrTime
     *
     * @return the value of t_user.lastRecordLoginErrTime
     *
     * @mbg.generated
     */
    public String getLastrecordloginerrtime() {
        return lastrecordloginerrtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.lastRecordLoginErrTime
     *
     * @param lastrecordloginerrtime the value for t_user.lastRecordLoginErrTime
     *
     * @mbg.generated
     */
    public void setLastrecordloginerrtime(String lastrecordloginerrtime) {
        this.lastrecordloginerrtime = lastrecordloginerrtime == null ? null : lastrecordloginerrtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}