package com.fastjrun.demo.entity;

public class UserLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.deviceId
     *
     * @mbg.generated
     */
    private String deviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.loginCredential
     *
     * @mbg.generated
     */
    private String logincredential;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.createTime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.logOutTime
     *
     * @mbg.generated
     */
    private String logouttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.inValidateTime
     *
     * @mbg.generated
     */
    private String invalidatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_login.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.id
     *
     * @return the value of t_user_login.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.id
     *
     * @param id the value for t_user_login.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.userId
     *
     * @return the value of t_user_login.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.userId
     *
     * @param userid the value for t_user_login.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.deviceId
     *
     * @return the value of t_user_login.deviceId
     *
     * @mbg.generated
     */
    public String getDeviceid() {
        return deviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.deviceId
     *
     * @param deviceid the value for t_user_login.deviceId
     *
     * @mbg.generated
     */
    public void setDeviceid(String deviceid) {
        this.deviceid = deviceid == null ? null : deviceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.loginCredential
     *
     * @return the value of t_user_login.loginCredential
     *
     * @mbg.generated
     */
    public String getLogincredential() {
        return logincredential;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.loginCredential
     *
     * @param logincredential the value for t_user_login.loginCredential
     *
     * @mbg.generated
     */
    public void setLogincredential(String logincredential) {
        this.logincredential = logincredential == null ? null : logincredential.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.createTime
     *
     * @return the value of t_user_login.createTime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.createTime
     *
     * @param createtime the value for t_user_login.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.logOutTime
     *
     * @return the value of t_user_login.logOutTime
     *
     * @mbg.generated
     */
    public String getLogouttime() {
        return logouttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.logOutTime
     *
     * @param logouttime the value for t_user_login.logOutTime
     *
     * @mbg.generated
     */
    public void setLogouttime(String logouttime) {
        this.logouttime = logouttime == null ? null : logouttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.inValidateTime
     *
     * @return the value of t_user_login.inValidateTime
     *
     * @mbg.generated
     */
    public String getInvalidatetime() {
        return invalidatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.inValidateTime
     *
     * @param invalidatetime the value for t_user_login.inValidateTime
     *
     * @mbg.generated
     */
    public void setInvalidatetime(String invalidatetime) {
        this.invalidatetime = invalidatetime == null ? null : invalidatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_login.status
     *
     * @return the value of t_user_login.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_login.status
     *
     * @param status the value for t_user_login.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}